### ISSUE TITLE
Update failed for menu

### ISSUE THREAD

**Issue by fakhruddin-vsbizz** [fakhruddin-vsbizz/mkitchen-ui#35]
Route: admin/menu

Description:
Can't update the already set menu.

**Comment by somesh2001** [comment]
Done - Handle the booth the cases
1. when the menu not created create one
2. when menu is already created update the menu data.

![Screenshot (882)](https://github.com/fakhruddin-vsbizz/mkitchen-ui/assets/56119880/b7c38cd1-c992-4e6a-b526-1e3e66a7d8b0)
![Screenshot (883)](https://github.com/fakhruddin-vsbizz/mkitchen-ui/assets/56119880/ea33b227-57b5-472e-91ef-675ed40c7286)
