### ISSUE TITLE
Duplication in items while confirming ingredient

### ISSUE THREAD

**Issue by fakhruddin-vsbizz** [fakhruddin-vsbizz/mkitchen-ui#37]
Route: pai/procurement

Description:
On 14th May, the ingredient list has 2 Haldi items. Please check for duplication.

**Comment by fakhruddin-vsbizz** [comment]
[Update]

When fetching from the frontend, multiple items must be converged to one when calling duplicate ingredients, and when submitted, the total amount must be the sum of all volumes of duplicate ingredients.

**Comment by somesh2001** [comment]
Done - Duplication is been removed and calculating the sum
